# Generated by Django 3.2.6 on 2021-08-25 09:41

from django.db import migrations


def create_stages(apps, schema_editor):
    Stage = apps.get_model('apis', 'Stage')
    db_alias = schema_editor.connection.alias
    Stage.objects.using(db_alias).bulk_create([
        Stage(level=1, time_amount=0, next_stage_id=2),
        Stage(level=2, time_amount=1, next_stage_id=3),
        Stage(level=3, time_amount=8, next_stage_id=4),
        Stage(level=4, time_amount=24, next_stage_id=5),
        Stage(level=5, time_amount=144, next_stage_id=6),
        Stage(level=6, time_amount=480),
    ])


def trucate_stages(apps, schema_editor):
    Stage = apps.get_model('apis', 'Stage')
    db_alias = schema_editor.connection.alias
    Stage.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_stages, trucate_stages)
    ]
